name: CI/CD with Docker

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: aliishah05
          password: d=-6i#ae)hHuk@L

      - name: Build and push Docker image
        run: |
          docker build -t aliishah05/mlops:latest .
          docker push aliishah05/mlops:latest

      - name: Run Docker container
        run: |
          docker run -d -p 4000:8080 aliishah05/mlops:latest
